### ISSUE TITLE
Migrate to another maven repo

### ISSUE THREAD

**Issue by DRSchlaubi** [pdvrieze/xmlutil#60]
Bintray shuts down next month: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Therefore this lib should switch to another repo in order to stay available:
- https://central.sonatype.org/pages/ossrh-guide.html
- https://jfrog.com/start-free/

**Comment by pdvrieze** [comment]
I'll be looking at it. I'm thinking about a coordinate change though. In the meantime I should at least be able to use github maven hosting.

**Comment by DRSchlaubi** [comment]
Using Github packages for maven is kinda annoying as even for public repositories you need to specify a GitHub private key if you want to download it. Also, there is almost no documentation on how to use it with Gradle.

Using jfrog platform is as easy as using bintray and can be setup very easily.
Maven Central is a bit more challenging because it requires a lot of steps but it also shouldn't really be a problem as it's well documented

**Comment by altavir** [comment]
You can use repo.kotlin.link to redirect calls to any repository you like. We've been using it for KScience projects and it is really good experience. It redirects calls based on package name.

**Comment by conorfarrell-coats** [comment]
Bintray had a planned brown-out today, so all of our pipelines failed :sweat: It would be great if Xmlutil could be moved to somewhere that isn't Bintray, happy to spend time assisting if necessary.

**Comment by DRSchlaubi** [comment]
It shouldn't be on bintray anywaYs as bintray is about to shutdown

**Comment by pdvrieze** [comment]
I've just put it on github packages (and updated the documentation). - Sorry I've been kind of busy with other things. I've also applied for a sonatype project.

Please note that the coordinates have changed (they were a mess and somewhat incompatible/problematic) - they are now basically what kotlin-mp and maven-publish do by default.

**Comment by ratabb** [comment]
github package need credential, I think documentation  should mention it.

To put credential, I use local properties (for running at local PC) and system environment (for running at github actions)

my playground: https://github.com/hishoot2i/Hishoot2i/blob/15dfc32689de7fe0f017dac759fd48afe690bffb/settings.gradle#L59-L66

**Comment by pdvrieze** [comment]
That's a bit silly for read only public access, but it seems to be a common issue (https://github.community/t/download-from-github-package-registry-without-authentication/14407/23). I'm in the process of putting it on mavencentral. That should resolve the usage issues once and for all.

**Comment by DRSchlaubi** [comment]
You can make docker packages public now but afaik you still can't do that for maven. GitHub packages is basically useless for maven because of this

**Comment by DRSchlaubi** [comment]
Looks like maven central approved this anyways so GHPR doesn't matter anymore: https://issues.sonatype.org/browse/OSSRH-67510?focusedCommentId=1044596&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1044596

**Comment by pdvrieze** [comment]
I've just managed to finish publishing it on sonatype: https://s01.oss.sonatype.org/content/repositories/releases/ and synchronizing to maven central should work.

**Comment by pdvrieze** [comment]
Publishing to maven central has been completed (search is still pending but should appear soon)
